name: saint_gobain
description: "A new Flutter project."

version: 1.1.0+1

environment:
  sdk: '>=3.3.1 <4.0.0'
dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.6
  logger: ^2.4.0
  get_storage: ^2.1.1
  google_fonts: ^6.2.1
  dio: ^5.6.0
  get: ^4.6.6
  package_info_plus: ^8.0.2
  image_picker: ^1.1.2
  geolocator: ^13.0.1
  geocoding: ^3.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0
  flutter_launcher_icons: ^0.13.1

flutter_launcher_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/logo/Saint_Gobain_Logo.png"
  min_sdk_android: 21 # android min sdk min:16, default 21

flutter:

  uses-material-design: true

  assets:
    - assets/logo/
    - assets/images/
